allure.results.directory=target/allure-results
allure.report.directory=target/allure-report
allure.logging.level=INFO
allure.link.issue.pattern=https://example.com/issue/{}
allure.link.tms.pattern=https://example.com/tms/{}
allure.report.title=Product of COMPANY.ORG Test Automation Report
allure.report.name=Product of COMPANY.ORG Test Suite
allure.categories.product_bug.pattern=Product bug
allure.categories.test_bug.pattern=Test bug
allure.categories.known_issue.pattern=Known issue
allure.report.version=2.29.0
allure.model.version=2.29.0
allure.timeline.enabled=true
allure.timeline.mode=packages
allure.behaviors.enabled=true
allure.packages.enabled=true
allure.suites.enabled=true
allure.attachments.enabled=true
allure.results.history.enabled=true
allure.results.trends.enabled=true
